sudo: required
services:
- docker
language: java
dist: bionic
jdk:
- openjdk14
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - DOCKER_IMAGE=gdvoesak97/imghandling1:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
  - secure: bM1lpwagLb2aM/kfRJPKGJBG+BOBJdYaKkNI6tnVrkNOtddxMFley0zC9+b0TddTZtsqUyeP64b3wR1fQ7ZkmK1GjBMryD7inH289BFcWecQyfQEexcDMrmijC9QP7ZQKV8tl6qmo3rhzDeD9f31ymLwWeH0boLhqSi4o14QDQRPuAxefO/QG2QrtR6B6J/KvfdQYGLw/bQyCyCFiZI7baC7iNlu3tp/yL3g5alUVRYjxzOlqBAxFsxyt3H1mkuHsgqnx/dscfeHdo144MhjaXRrKRtENTGp4DbDLTvU5wb8az8C4KWd6avyxO59UIGwXOvFZZdHfQeITD8nODFxVUYiZZSWIYtuxkBP6r8cvKZKROqzNk41K6yTYpRKLxcwn9jM3vzjctL5hhg2MbmsJWiwX37UhL8Z/JqEVUVktreI0L6wFAU3TuWzF76xW/YSpSKgMJJ6V3Y4UvV+Uq2DiVbQeiqZjT4GD3nCw2aJdDUUS4ShKGjQBc7rXybvc04dtfq35Az51royl25RhaiAvtpYBaX0rfgyVlji/TT2p32VxOYQXMGtiNu9nQ1otNtnLpCKLUOOQuxoz859LaOruR4RzPEHbyONDg57d1Y9TUJvmD9p5JP+wZBrdCoLkLWvvSmve9mq60fG1NBCa/FbuC5zAWQaKwU3k0lewsWhBlw=
  - secure: fKrcdY0bKHR40tnsj67BUaqWxr9i3nrAnLit47WyKIC1VGdSnYVB2OulxW/zcCfLdicChvQCcs1kqevuBjuY9Benmrj+H6yadCkOk4ivzMeIHoafSPuP6Z4cojNFdedPjMol8a15YhRhi23LVSE7SGBDF4N/u1n2rrCiG/WROSBtr2XaS2+rIVNm6awfTa5FOjSYa0fmDPoCg6oXXxSkCp8m3LUm/Uzu8LLEIMGBVCK3ZvC1HjaqkgfpsYKXA3yP3BjVcEq0/zGuKRxOzQiv88rjTNjVKVCe1EJYMdnTOWj6XXsKPgtIqGAUzkt6unmdIS8lJk7jeZXlpiLMzTswxYA5fnP31/lW7Sk23OT10dt9XVrbPgC5J1nPv3PUnEwfdiOjGZgD79H2rqPd2lTZWcHctqqbjs+27xZQoa58r+vlO511bp2CMokiqy1xnvBm3oHG2UCsYDkUtcLsH3NqrwopAP5ry2WjXFRH3XhvmaG+cFTh9DQZ+EYN+q7N5oWIAIoM7kCKrK5ZPoeY6H0YWLtu8FENliNfelsj/4MUN1FFbvYNtci4JE5A9JaHyf3wml31Z6VKNhRchQq0KNjqNA9a7YRfkJNM4wS//e954SuE2uA1ZkzzvwFIJUrLQ0C/mgnkctcUPSg3JwUAK0hluSEoojblm2mHNqOwWDG6auM=
script:
- mvn clean package -U
- docker build -t "$DOCKER_IMAGE" .
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push "$DOCKER_IMAGE"