sudo: required
services:
- docker
language: java
dist: bionic
jdk:
- openjdk14
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - DOCKER_IMAGE=rsogalerija/imghandling:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
  - secure: R38+h3fWPzVVPsowHPhEv7v58Hf/dRLETj3IvoQIGDGzvXbrEcIcWHXNvRXZ8NxGUDcB6dwRXe5YmS6LYnZ/vuSzmbAbSbNX4xy8X5kqMOuXJUd3xRP8HSXJ5keL75hhopSBiIGtUUMIwUegwGiWtpPmeYckiMkB9a2txjYVkAHBBeDGIl03dU/j7biLvwpPwZOiIakynKViTtd73x8EKK8d9iO6HwmBctctXbI+XN3JFp18vfHdb3zFgf+KHuu5bZOOHiPlmTIcELtZ9Cb1iYqFXBqLLfw3zxgWtcYSErV9vKSAOoQ6CGIsOeCrWVoQvjQD3/O1+2LvVzgIhne8qR6DeS4fy7XNzW+EFJWvVU2juIe+qwzwWQAXSFZ7xa3ksbo9cgTlYPhkuRxqwhJssiXAM7nricGlB3Q6WY9KsIYHpQNLSPpgowZALLmDPAHLii2JA73TQM5J3eOUWpdohcjTLo87s0LK+ThEDxEta0W580nxwQPV1RIPh5KhYUux8B2kVpzhFbcxPOxpEKTGuM6Z3iyVHJLEfwX25F/PCQqeZPlhvJtXMHM+7fU6vEWc5bAsMT4rWzprQZ05oQzlFWzexIYQ0JM8nzyXkb3jxYxwxyrPo47EbhyrrIYRYOviJhNVvpfb8P8rLkqApgW6HkaG/IX4A3TLzfE4KUwdxuk=
  - secure: CzM9rMRtN4cM8bK18zjZTyAIwC9XxIirKWcwqgtTHVi9+VjzruRXUUr+loADjT74t+3vn0LkenFFmgmY9alqrBRgzbWmy8dgeQLFPzjAkbqQCX5Es6YfXPe7BxNvTvxJ6v7zD0OQVUElBoYec67aQpV+D1rSl8uM+Mp2QXeQ9BQYpAIy3hEcX/XixuJlpUJyOobWYFjQg+sS5wh3Ba/tRL1+p+K/d5AUcvDM3APp5yobUFcST7apDo1bnRqMJ+eCBqPKO8POiOmAGuzO26lhISBebJhqit9yrRucpcoT7rbEZJNJBB7daIT3NogctibTat6dj453SH6eeJq6TWLKqTGdO+/QEzyfWKcHx8YtfwkF35ylIC1oGHdelnXJdlFip/c6jrly/Ro1zqbvFv4WSfKLFY8GOrl07ahLRU8BwBhcUYZ9+g7TTeOHpYa6JFVhSA9Sw8EZ3/ZaobRKPb5kPZjldKDbbMX4GYV4coAUQTSSuSI3Sf5coPdJ1MKSC/eCC9HTnsR9ZcLbay/eI74tJ7DFhgeYnIxBaQko+Eai/sIU8147VcD7Wpo4pG+A0O4Rav6Y10EsKF6R7hyDGpWN9adeQnwzRLBYjX410jVoBVXhDc4J9Ycy/WzU+OaRRULncCH9Vxf/mf4XgYPzer7gSE9dTwoB6Nzq4U3nTAli3is=
script:
- mvn clean package -U
- docker build -t "$DOCKER_IMAGE" .
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push "$DOCKER_IMAGE"