sudo: required
services:
- docker
language: java
dist: bionic
jdk:
- openjdk14
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - DOCKER_IMAGE=rsogalerija/imagehandling:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
  - secure: OzEk26SNbU0aqsBYlsOACcW0k/hZlS+m7rrIWdmyp+K4YuRX9Dy2oVS4myMFYVU46MgtzouTPkhUDoemwlOlujZHwcFH1wDLcd1MO0uhJrkuwSgzU2lRTZj3sleFyznE3a0INiMsIa7BTuxW37EP+W6TEb5ZS+Ac+y+VoieigQ8t3TbBP3mWyninQUitNVbS6Y1qj36jpqAQZbkEfQHwQITxpfaIu+FtJPU6pv7W/Pc+dsY8+LU5aMB95gx6YhuPbw7Rn3MAROsLXef4ZTyLq1JsbPTqydEdQzCxshp5cSTXhxBawSOQNCbZdoNUPPQxn3wfYKM+OpksXor5rHtzVv+3n4qk+qjWHGCJeoAaY/IY9KW9OkSRBhZPdBnlr5FghNY4lRDKVoQO/ZHHRUIt7Tm9oSNEUudVw8MqOrlO0K352Y8jMBshTuos/tswZpQVAK9DKJR5rBWk0CYqOj6JO0nM0xBdYnLVikqbldJZejwfBnM+1iNt5iCucgm50nGfHHHsY0hK/n7aUZLB4BbEKNLEINnCC/WKcjUC2y11HqdvC0AU1IrRC4WOnKSb7fFw3qy5GylF9zjVJxq5CBQlGIj8ChoXoew+tBA4715Cf7b83oVFVdlMM9YbeTUy8LmQ+tFHbG1AFxUKs8AyEEUKrenyNflTfCj+GWsRjxFumfg=
  - secure: DLhLPJYcpnI326FK0AxjUIuX+WkmfZ1Iv6Y5Rwj0JQOCuYhEiGM8J1Jq69blfJZLIokvW31pa6sOLoIu3EyjbN2MlMJGuCi1XsmEzxFSqDuLtx8cRvs9VhJzJ9wsmVzc4T0JR3NGzMtIX/sUcVumQ+tBDx3aMta04iqGiR8Zs+NpmWUGHgTa0ow+SM3xpcc4BJZJz1MQaY+yr9Z9QpzOG4glAu9gfLOzy3bVklauiA6CYCpPVU98/p5zVP66on2IH8X7PM8Ii00yA9Hvsy71ULUwNv5zo/nIuUqfHhJgtTJY6oE0OFrQws04p/2UK6RrbR9ZZyYjRJyGv4qe8Ghb+Vq+EO88FcrPNUthdk0JfPv4CnSszLU1uCIMDncWC0fMiiPL84KHXHlbUFHhpXKR0ovi3i5DTMkLSAc42P47WGgZYhJxxOzUMyF7WLXbbjzMhcGr7yNhsrWB4wsQaPm2Y3PRp1iaBLK1X/8TsLhXpSyT+l/9A5SpFNZ0DbtIzsV5CuzIfo5rbwdR9+8txjMZvpEKHibv6XkzSez5dXOe3A4k7TkUByBFCYfR5nyIBR+aXYwC1K6kARfFmH/OZWrslZ7VcHd2yRixp3oRtAmbDK2a29sr13Nsses4Qxg5EeBpqM840ImoiUqI0iWi3hpkoFwTcHqbxY9b/Dk4rwwr+2M=
script:
- mvn clean package -U
- docker build -t "$DOCKER_IMAGE" .
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push "$DOCKER_IMAGE"