sudo: required
services:
- docker
language: java
dist: bionic
jdk:
- openjdk14
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - DOCKER_IMAGE=gdvoesak97/imghandling1:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
  - secure: oYf5bWp6uyjOinl/QBL4YbSKAjBz4nl/4nTKASFmrB+006BTJtE2cZxDfZ02fb2X45FdiuL3b22viFsm2sfjj3SVcUkxxdU4gM8rjVzqDyeuKpAtx/C75wzwXSvfhtHxgisxbIv3S2cmiumbTSVqdXd1RXz7SOQykSxKJ7QTaJakyqJPxvH3wemHxJukLq7ZWsexgnnOJSHYSKR7XOURY0n3CqIacnRAo1rQXdXuDVdkGpZryqvroBbO5wmSrKPJJ2FuP0ZElakBf4cecaOj5OOENhzKXCXl2TgvayWdiR3tOtZXDz4+pkSisncSVBtqG7UKssNJMBCiBanmhq1tJEuG7mUjm/GgqTXahPPlaIPXAIZJrHvTcEp0Y+PgVTjDQjUV4KyVzYscdbxzU6PuaWrLzW+Eo7R43nn5SBGPjVtK2RSxyQkB/3U5ZAkSN94QMI0ZfapEfxBGJgQySZuJP7oyh/gQD5SmNtSkEolbi5HUl6d+X6ziof0zJ9hRGKThxfEhQSt9dg6M4y3FUkv2NQ8W7MxujFtjTvTVoPungRBZykKVmguOBS1KfOk5FyK0j+tp+surTeU07eU3PYqk6VRuzieSzf7r34nYVYq3cUg/t9eCAyO63oOxEpS6RnsZlRJ4qcYlemZbibA56rI7vdV9F9Y9ywBaLqlg+P+w8VY=
  - secure: N+lLJvEAhPZ3SnkVJ8ykufmiCFfBt/r06uJT+48D50YCSb7ia5Q/FwNYvvYnAniIwPDVQ7IQYvwdUjaFy1G+rTuFz5LezeGl05sWml4CIPU/EZZzlAhypw/V59bhJLbSj2cUAaxQlIpseuVq4hvQe450rCvE9SwEQIKyAmyGRqe1n/1XH9ERdILYGjzvBeOvn6HDrp3EQDPw5fh2FKiHVTGvKPYJXOtZdEiyCl0qMmFaPr8YqQ9uMlQnni1B6+cenAONm0Hk7G4J9jJV/dJ2Nb6rSVUYSZPCC9uJW+WhMJc7uqQzpOzLMQ4ZCbC/H7mgELor1NHu4SW+x9W2yvdCiGXjfFgqCcWIRJQnYRE03FNktCNoK0RhN6f8V+Y792nkdM1gAh1+E8znezQgaamH3n2kQM01COg3lknFZXirCm2oZ1iH7jUskedj287CyQf/dx6q+YsbaJZp5+d0oXkKJpQcMlBu8bU7cKNv3r/osfco4VnqxVU/PzFwVFbTDgDAyvBlIQDa1SWXJdhb223wLN8oK0XZLF98kGQf/O4vDQr0IyFSOBRgI1bvgUeHgsWyCLF1Sr4oNaHSc+aZeQHwUsfxEmtCU9ocUSuAl5NA0zosq/PX/TUZvx2T2XXTsLONo85MLMNL1NfdDDYfAJFAN3iwKYqFqfhjOyQfznh2Ydg=
script:
- mvn clean package -U
- docker build -t "$DOCKER_IMAGE" .
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push "$DOCKER_IMAGE"