kumuluzee:
  name: image-handling-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ImageHandlingDS
      connection-url: jdbc:postgresql://suleiman.db.elephantsql.com:5432/qqvsuwix
      username: qqvsuwix
      password: QqKJn0QkHNGIkto-Y9CqUuvE_EQHtJMi
  health:
    checks:

      disk-space-health-check:
        threshold: 100
  metrics:
    web-instrumentation:
      - name: images-enpoint
        url-pattern: /v1/images/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                <Configuration name="comments">
                    <Appenders>
                        <Console name="console" target="SYSTEM_OUT">
                            <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                        </Console>
                        <Socket name="logstash" host="7da8ca12-a484-4e33-9f31-47560a83a328-ls.logit.io"
                        port="18461" protocol="udp">
                            <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                        </Socket>
                    </Appenders>
                    <Loggers>
                        <!-- Default logger -->
                        <Root level="all">
                            <AppenderRef ref="console" level="info" />
                            <AppenderRef ref="logstash" level="trace" />
                        </Root>
                    </Loggers>
                </Configuration>'
rest-properties:
  dev-mode: false
  broken: false